<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Resource Management</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A preview of the jQuery UI Bootstrap theme">
		<meta name="author" content="Addy Osmani">

		<!-- Le styles -->
		<link href="/assets/css/bootstrap.min.css" rel="stylesheet">
		<link type="text/css" href="/css/custom-theme/jquery-ui-1.10.0.custom.css" rel="stylesheet" />
		<link type="text/css" href="/assets/css/font-awesome.min.css" rel="stylesheet" />
		<!--[if IE 7]>
		<link rel="stylesheet" href="/assets/css/font-awesome-ie7.min.css">
		<![endif]-->
		<!--[if lt IE 9]>
		<link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.10.0.ie.css"/>
		<![endif]-->
		<link href="/assets/css/main-style.css" rel="stylesheet">
		<link href="/css/custom-style.css" rel="stylesheet">
		<link href="/assets/js/google-code-prettify/prettify.css" rel="stylesheet">

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Le fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="/assets/ico/favicon.png">
		<link rel="stylesheet" href="/assets/css/chosen.css" />

		<script src="/assets/js/jquery-1.9.0.min.js" type="text/javascript"></script>
		<script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="/assets/js/jquery-ui-1.10.0.custom.min.js" type="text/javascript"></script>
		<script src="/assets/js/google-code-prettify/prettify.js" type="text/javascript"></script>
		<script src="/assets/js/docs.js" type="text/javascript"></script>
		<script type="text/javascript" src="/assets/js/chosen.jquery.min.js"></script>
		<!--<script src="/assets/js/demo.js" type="text/javascript"></script>-->

	</head>

	<body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">

        <!-- Navbar
        ================================================== -->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
              
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active">
                                <a href="<?php echo $this->url('home') ?>">Home</a>
                            </li>
							 <li class="active">
                                <a href="<?php echo $this->url('home') ?>">Booking</a>
                            </li>
							 <li class="active">
                                <a href="<?php echo $this->url('home') ?>">Type</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('home') ?>">Resource</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('home') ?>">User management</a>
                            </li>
							 <li class="active">
                                <a href="<?php echo $this->url('zfcuser/login') ?>">Login</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('zfcuser/register') ?>">Register</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('zfcuser/logout') ?>">Log out</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('zfcuser/changepassword') ?>">Change password</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('zfcuser/changeemail') ?>">Change Email</a>
                            </li>
							<li class="active">
                                <a href="<?php echo $this->url('zfcuser/authenticate') ?>">authenticate</a>
                            </li>
                    </div>
					  
                </div>
            </div>
        </div>


        <!-- Subhead
        ================================================== -->
		<?php echo $this->partial('partials/header', array()); ?>

        <div class="container">
			<!-- Docs nav ================================================== -->
			<div class="row">
				<div class="span3 bs-docs-sidebar">
					<?php echo $this->partial('partials/left-nav-bar', array()); ?>
				</div>
				<div class="span9">
					<?php echo $this->content; ?>
				</div>
			</div>
			<!-- Footer ================================================== -->
			<?php echo $this->partial('partials/footer', array()); ?>

			<!-- Placed at the end of the document so the pages load faster -->
	</body>
</html>